name: Automated API tests using Newman

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Newman
        run: npm install -g newman
      
      - name: Run API tests with Newman
        run: |
          newman run "/home/runner/work/anw_dashbold_backend_qa/anw_dashbold_backend_qa/postman/collections/Dashbold API V.1.0.0.json" \
            -e "4532654-5fb38c9c-a3f8-49ed-8549-7f0840b61018" \
            --reporters cli,junit,html \
            --reporter-junit-export "postman-reports/Automated_API_Tests_Report.xml" \
            --reporter-html-export "postman-reports/Automated_API_Tests_Report.html"
      
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: Automated API Tests Reports
          path: postman-reports/
